### PR TITLE
new user creation

### PR DESCRIPTION
**Pull request by RomaZinkevich**

### CODE REVIEW

**Review by ZealinBee — CHANGES_REQUESTED** [review]
Make try catch in the controller layer 
Make db throw error back to controller with appropriate error message and status so controller can res.json the error

**Comment by ZealinBee** [comment]
apparently it's common practice in express to make error handling middleware and custom exception function for centralized error handling
Error Middleware Video: https://www.youtube.com/watch?v=WXa1yzLR3hw
```
// Error-handling middleware
app.use((err, req, res, next) => {
  if (err instanceof CustomException) {
    // Log the error for debugging
    console.error(err.stack);

    // Respond with a user-friendly error message
    res.status(err.status).json({ error: err.name, message: err.message });
  } else if (err.status === 404) {
    // Handle 404 Not Found errors
    res.status(404).json({ error: 'Not Found', message: 'The requested resource was not found.' });
  } else {
    // Handle other types of errors
    console.error(err.stack);

    // Respond with a generic error message
    res.status(500).json({ error: 'Internal Server Error', message: 'Something went wrong.' });
  }
});
```
```
// Custom exception constructor
function CustomException(message, status) {
  this.name = 'CustomException';
  this.message = message || 'Default Custom Exception Message';
  this.status = status || 500;
}
```

**Comment by RomaZinkevich** [comment]
Don't pull yet, I want to add tests first

**Review by ZealinBee — APPROVED** [review]
looks good to me

**Pull request merged**
